#!/bin/sh -e

# setup will build everything in --release mode anyway.
# Running tests in --release will be faster overall.
BUILD=--release

./setup -d list

cargo fmt --check
cargo clippy $BUILD -- -Dwarnings  # Treat warnings as errors.
cargo test $BUILD
