#!/bin/sh -e

load_via_shell() {
    ENVIRONMENTD="$HOME/.config/environment.d"
    set -a
    if [ -d "$ENVIRONMENTD" ]; then
        for conf in "$ENVIRONMENTD"/*.conf
        do
            . "$conf"
        done
    fi
    set +a
}

load_via_systemctl() {
    set -a
    eval $(systemctl --user show-environment)
    set +a
}


if command -v systemctl >/dev/null 2>&1; then
    load_via_systemctl
else
    load_via_shell
fi

exec "$@"
