[workspace]
resolver = "2"
members = [
    "bootstrap",
    "pikaconfig",
]

# https://doc.rust-lang.org/cargo/reference/workspaces.html#the-package-table
[workspace.package]
version = "0.1.0"
edition = "2021"
rust-version = "1.84.0"
