[workspace]
resolver = "2"
members = ["crates/*"]

# https://doc.rust-lang.org/cargo/reference/workspaces.html#the-package-table
[workspace.package]
version = "0.0.0"
edition = "2024"
rust-version = "1.85.0"

[workspace.dependencies]
anyhow = "1.0"
dirs = "6.0"
either = "1.13.0"
log = "0.4"
pretty_assertions = "1.4.0"
serde = { version = "1.0", features = ["derive"] }
test-case = "3.3.1"
thiserror = "2.0"

[workspace.lints.clippy]
str_to_string = "deny"
[workspace.lints.rust]
unreachable_pub = "deny"
