[package]
name = "pikaconfig"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
anyhow = "1.0"
base64 = "0.21.0"
clap = { version = "4.2", features = ["derive"] }
dirs = "5.0"
glob = "0.3.1"
indoc = "2.0.1"
log = "0.4"
once_cell = "1.17.1"
serde = { version = "1.0", features = ["derive"] }
serde_yaml = "0.9.21"
sha2 = "0.10.6"
shellexpand = "3.1"
shlex = "1.1.0"
stderrlog = "0.5.4"
sysinfo = { version = "0.28.4", default-features = false }
thiserror = "1.0"
toml = "0.7.3"
ureq = "2.6.2"
walkdir = "2"
which = "4.4.0"
xdg = "^2.4"
