#!/bin/sh -e

# Supports methods such as native or docker.
# See <setup>_setup helpers.
USE_SETUP="${PIKACONFIG_SETUP:-native}"

dispatch_setup_helper() {
    log Using "${USE_SETUP?}" setup
    "${USE_SETUP?}_setup" "$@"
}

src_root() {
    cd "$(dirname "$0")"
    pwd
}

SRC="$(src_root)/pikaconfig"

log() {
    echo "$@" >&2
}

log_eval() {
    log '$' "$@"
    "$@"
}

fatal() {
    log "$@"
    exit 1
}

get_rust() {
    if cargo --version >/dev/null 2>&1; then
        log "Using existing cargo"
        return
    fi
    # Use https://rustup.rs/ as package managers often don't have new enough
    # rust toolchain.
    curl --proto '=https' --tlsv1.2 -sSf https://sh.rustup.rs | sh
}

native_setup() {
    get_rust
    cargo run --manifest-path="${SRC?}/Cargo.toml" --release -- "$@"
}

base_docker_setup() {
    mkdir -p "${SRC?}/target/release"
    log_eval $OPTIONAL_SUDO docker run \
        --volume="${SRC?}/cargo-registry:/usr/local/cargo/registry" \
        --volume="${SRC?}:/app" \
        --rm \
        --workdir=/app \
        rust:latest \
        cargo build --release
    "${SRC?}/target/release/pikaconfig" "$@"
}

docker_setup() {
    base_docker_setup "$@"
}

sudo_docker_setup() {
    OPTIONAL_SUDO=sudo
    base_docker_setup "$@"
}

dispatch_setup_helper "$@"
