#!/bin/sh

# PNG is much faster to load than PPM, using PNG allows for more seamless
# transition between the actual workspace and the captured image.
src_format=png

# The most common lossless format.
dst_format=png

# This must match config.d/screenshot window criteria.
filename_prefix=sway_grim_screenshot

# Singleton.
if pidof -o %PPID -x "$0"; then
    exit 0
fi

screenshot="$(mktemp --suffix "$filename_prefix.$src_format")"
grim -t "$src_format" "$screenshot"
imv-wayland "$screenshot" &
imv_pid=$!

while [ -z "$(swaymsg -t get_tree | grep imv)" ]; do
    continue
done

get_crop() {
    slurp -d | sed -r 's|([[:digit:]]+),([[:digit:]]+) (.+)|\3+\1+\2|'
}

# A more efficient way would be to reuse the "$screenshot", but unfortunately
# the $screenshot has full physical resolution, and slurp returns relative
# resolution. They don't match if scaling is enabled. As a workaround we can
# just take another screenshot and let grim cut it for us on the spot.
# convert -crop "$(get_crop)" "$screenshot" "$dst_format:-" | wl-copy -t "image/$dst_format"
slurp | grim -g - - | wl-copy -t "image/$dst_format"

kill -s KILL "$imv_pid"
rm "$screenshot"
