#!/bin/sh -e

# PNG is much faster to load than PPM, using PNG allows for more seamless
# transition between the actual workspace and the captured image.
src_format=png

# The most common lossless format.
dst_format=png

# This must match config.d/screenshot window criteria.
filename_prefix=sway_grim_screenshot

# Singleton.
if pidof -o %PPID -x "$0"; then
    exit 0
fi

get_focused_output_info() {
    swaymsg -t get_outputs | jq -r '.[] | select(.focused) | {name, scale, rect}'
}

focused_output_info="$(get_focused_output_info)"

get_focused_output_name() {
    echo "$focused_output_info" | jq -r '.name'
}

get_focused_output_scale() {
    echo "$focused_output_info" | jq -r '.scale'
}

get_focused_output_x_offset() {
    echo "$focused_output_info" | jq -r '.rect.x'
}

get_focused_output_y_offset() {
    echo "$focused_output_info" | jq -r '.rect.y'
}

screenshot="$(mktemp --suffix "$filename_prefix.$src_format")"
grim -o "$(get_focused_output_name)" -t "$src_format" "$screenshot"
imv-wayland "$screenshot" &
imv_pid=$!

while [ -z "$(swaymsg -t get_tree | grep imv)" ]; do
    continue
done

get_crop() {
    selection="$(slurp -d -f '{ "w": "%w", "h": "%h", "x": "%x", "y": "%y" }')"
    awk "BEGIN {
        w = $(echo "$selection" | jq -r '.w')
        h = $(echo "$selection" | jq -r '.h')
        x = $(echo "$selection" | jq -r '.x')
        y = $(echo "$selection" | jq -r '.y')
        x_offset = $(get_focused_output_x_offset)
        y_offset = $(get_focused_output_y_offset)
        scale = $(get_focused_output_scale);
        print w*scale \"x\" h*scale \"+\" (x-x_offset)*scale \"+\" (y-y_offset)*scale
    }"
}

convert -crop "$(get_crop)" "$screenshot" "$dst_format:-" | wl-copy -t "image/$dst_format"

kill -s KILL "$imv_pid"
rm "$screenshot"
