#!/bin/sh -e

load_env_via_shell() {
    ENVIRONMENTD="$HOME/.config/environment.d"
    set -a
    if [ -d "$ENVIRONMENTD" ]; then
        for conf in "$ENVIRONMENTD"/*.conf
        do
            . "$conf"
        done
    fi
    set +a
}

load_env_via_systemctl() {
    set -a
    eval $(systemctl --user show-environment)
    set +a
}

load_wayland_env() {
    export MOZ_ENABLE_WAYLAND=1
    export SDL_VIDEODRIVER=wayland
    export CLUTTER_BACKEND=wayland
    export QT_QPA_PLATFORM=wayland
}

load_env() {
    if command -v systemctl >/dev/null 2>&1; then
        load_env_via_systemctl
    else
        load_env_via_shell
    fi
    if [ -n "$WAYLAND_DISPLAY" ]; then
        load_wayland_env
    fi
}

add_to_path() {
    local path="$1"
    case "$PATH" in
        # Don't add to $PATH if it is already there.
        *":$path:"*) ;;
        "$path:"*) ;;
        *":$path") ;;
        # Do add to $PATH if it's not.
        *) export PATH="$path:$PATH" ;;
    esac
}

load_opt_path() {
    for path in ~/.local/opt/*; do
        add_to_path "$path"
    done
}

load_cargo_path() {
    local cargo="$HOME/.cargo/bin"
    if [ -d "$cargo" ]; then
        add_to_path "$cargo"
    fi
}

load_go_path() {
    local gopath="$HOME/.go/bin"
    if [ -d "$gopath" ]; then
        add_to_path "$gopath"
    fi
}

try_ssh_agent() {
    local sock
    for sock in "$@"; do
        if [ -S "$sock" ]; then
            export SSH_AUTH_SOCK="$sock"
            return
        fi
    done
}

add_ssh_agent() {
    if [ -z "$SSH_TTY" -a \
         -z "$SSH_CONNECTION" -a \
         -z "$SSH_CLIENT" -a \
         -z "$TMUX" ]; then
        try_ssh_agent \
            "$HOME/.1password/agent.sock" \
            "$XDG_RUNTIME_DIR/ssh-agent.socket"
    fi
}

load_env
add_to_path "$HOME/.local/bin"
load_opt_path
load_cargo_path
load_go_path
add_ssh_agent

exec "$@"
