#!/bin/sh -e

try_terminal() {
    if command -v "$1" >/dev/null 2>&1; then
        echo '$' "$@" >&2
        exec "$@"
    fi
}

if [ -n "$WAYLAND_DISPLAY" ]; then
    try_terminal alacritty
    try_terminal kitty
    try_terminal foot
    try_terminal ptyxis --new-window
    try_terminal gnome-terminal
    try_terminal konsole
    echo Unable to find Wayland terminal, aborting >&2
elif [ -n "$DISPLAY" ]; then
    try_terminal alacritty
    try_terminal kitty
    try_terminal foot
    try_terminal ptyxis --new-window
    try_terminal gnome-terminal
    try_terminal konsole
    try_terminal xterm
    echo Unable to find X11 terminal, aborting >&2
else
    echo Unknown session type, aborting >&2
fi
