[package]
name = "lontra-glob"
version.workspace = true
edition.workspace = true
rust-version.workspace = true

[lints]
workspace = true

[dependencies]
anyhow.workspace = true
glob = "0.3.1"
log.workspace = true

[dev-dependencies]
pretty_assertions.workspace = true
test-case.workspace = true
