[package]
name = "lontra-git"
version.workspace = true
edition.workspace = true
rust-version.workspace = true

[lints]
workspace = true

[dependencies]
anyhow.workspace = true
process_utils = { path = "../process_utils" }
