# {{ header("#") }}

[general]
import = [
    {%- for path in glob("alacritty.d/*") %}
    {{ path | enquote() }},
    {%- endfor %}
]
{%- if is_windows %}
# Alacritty closes on Windows when configs are regenerated.
# TODO: Figure out why.
live_config_reload = false
# By default alacritty starts in C:\Windows\System32
working_directory = {{ home_dir() | enquote }}
{%- endif %}
