[package]
name = "git-signing-key"
version = "0.0.0"
edition = "2024"
rust-version = "1.88.0"

[workspace]

[dependencies]
anyhow = "1.0.98"
clap = { version = "4.5.41", features = ["derive"] }
shellexpand = { version = "3.1.1", features = ["path"] }
xshell = "0.2.7"
