use std::sync::Arc;

use anyhow::Result;
use indoc::formatdoc;
use minijinja::{Environment, Value};

use crate::jinja::{Context, map_anyhow};

/// Usage:
/// # header("#")
fn header(ctx: &Context, prefix: &str) -> Result<Value> {
    let sep = if prefix.is_empty() { "" } else { " " };
    let header = formatdoc! {"
    Autogenerated. See
    {prefix}{sep}{source_file}
    ",
    prefix=prefix,
    source_file=ctx.source_file.to_string_lossy()}
    .trim_end()
    .to_owned();
    Ok(Value::from_safe_string(header))
}

pub(super) fn register(env: &mut Environment, ctx: &Arc<Context>) {
    let ctx = Arc::clone(ctx);
    env.add_function("header", move |prefix: &str| {
        header(ctx.as_ref(), prefix).map_err(map_anyhow)
    });
}
