# Source: https://github.com/sxyazi/yazi/blob/latest/yazi-config/preset/keymap.toml

# A TOML linter such as https://taplo.tamasfe.dev/ can use this schema to validate your config.
# If you encounter any issues, please make an issue at https://github.com/yazi-rs/schemas.
"$schema" = "https://yazi-rs.github.io/schemas/keymap.json"

# https://yazi-rs.github.io/docs/configuration/overview/
# https://yazi-rs.github.io/docs/configuration/keymap/
# Prepend has higher priority.

[manager]
prepend_keymap = []
append_keymap = []

[tasks]
prepend_keymap = []
append_keymap = []

[select]
prepend_keymap = []
append_keymap = []

[input]
prepend_keymap = []
append_keymap = []

[completion]
prepend_keymap = []
append_keymap = []

[help]
prepend_keymap = []
append_keymap = []
