# Source: https://github.com/sxyazi/yazi/blob/latest/yazi-config/preset/theme.toml

# A TOML linter such as https://taplo.tamasfe.dev/ can use this schema to validate your config.
# If you encounter any issues, please make an issue at https://github.com/yazi-rs/schemas.
"$schema" = "https://yazi-rs.github.io/schemas/theme.json"

[icon]
prepend_rules = [
    { name = "Sync/", text = "󰴌" }
]
append_rules = [
    # Fallback wildcard rules.
]
