alias assh='ssh -o UserKnownHostsFile=/dev/null -o StrictHostKeyChecking=no'
alias df='df -h'
alias du='du -sh'
alias emacs='emacs -nw'
alias fbi='fbi -a $argv'
alias feh='feh --scale-down'
alias rplayer='mplayer -loop 0 -shuffle'
alias psc='ps xawf -eo pid,user,cgroup,args'
alias most='most -w'
