[package]
name = "lontra-registry"
version.workspace = true
edition.workspace = true
rust-version.workspace = true

[lints]
workspace = true

[dependencies]
anyhow.workspace = true
lontra-strings = { path = "../lontra-strings" }
rusqlite = { version = "0.35.0", features = ["bundled"] }
rusqlite_migration = "2.1.0"

[dev-dependencies]
pretty_assertions.workspace = true
test-case.workspace = true
