[package]
name = "tag_util"
version.workspace = true
edition.workspace = true
rust-version.workspace = true

[lints]
workspace = true

[dependencies]
anyhow.workspace = true
libc = "0.2.147"

[dependencies.sysinfo]
version = "0.33.0"
default-features = false
features = ["system"]
