[editor]
line-number = "absolute"

[editor.whitespace.render]
space = "none"
tab = "all"
newline = "none"

[editor.indent-guides]
render = true

[keys.normal]
"j" = "move_char_left"
"k" = "move_visual_line_down"
"l" = "move_visual_line_up"
";" = "move_char_right"

[keys.normal.g]
"h" = "no_op"
"j" = "goto_line_start"
"k" = "move_line_down"
"l" = "move_line_up"
";" = "goto_line_end"

[keys.select]
"h" = "no_op"
"j" = "extend_char_left"
"k" = "extend_visual_line_down"
"l" = "extend_visual_line_up"
";" = "extend_char_right"

[keys.select.g]
"h" = "no_op"
"j" = "goto_line_start"
"k" = "extend_line_down"
"l" = "extend_line_up"
";" = "goto_line_end"

[keys.normal.C-w]
"C-h" = "no_op"
"C-j" = "jump_view_left"
"C-k" = "jump_view_down"
"C-l" = "jump_view_up"
"C-;" = "jump_view_right"

"h" = "no_op"
"j" = "jump_view_left"
"k" = "jump_view_down"
"l" = "jump_view_up"
";" = "jump_view_right"

"H" = "no_op"
"J" = "swap_view_left"
"K" = "swap_view_down"
"L" = "swap_view_up"
":" = "swap_view_right"

[keys.normal.space.w]
"C-h" = "no_op"
"C-j" = "jump_view_left"
"C-k" = "jump_view_down"
"C-l" = "jump_view_up"
"C-;" = "jump_view_right"

"h" = "no_op"
"j" = "jump_view_left"
"k" = "jump_view_down"
"l" = "jump_view_up"
";" = "jump_view_right"

"H" = "no_op"
"J" = "swap_view_left"
"K" = "swap_view_down"
"L" = "swap_view_up"
":" = "swap_view_right"
