theme = "dracula"

[editor]
color-modes = true
line-number = "absolute"
true-color = true

[editor.whitespace.render]
# TODO: trailing whitespace
# https://github.com/helix-editor/helix/pull/7215
space = "none"
tab = "all"
newline = "all"

[editor.indent-guides]
render = true

[keys.normal]
G = "goto_file_end"
V = ["extend_to_line_bounds", "select_mode"]
# xd should remove empty line
# https://github.com/helix-editor/helix/discussions/835#discussioncomment-1481068
x = "extend_to_line_bounds"
X = "extend_line_below"
