[package]
name = "lontra-unarchiver"
version.workspace = true
edition.workspace = true
rust-version.workspace = true

[lints]
workspace = true

[dependencies]
anyhow.workspace = true
lontra-process = { path = "../lontra-process" }
