[package]
name = "os_str"
version.workspace = true
edition.workspace = true
rust-version.workspace = true

[dependencies]
anyhow = "1.0"
thiserror = "2.0"

[dev-dependencies]
pretty_assertions = "1.4.0"
