[package]
name = "dir_layout"
version.workspace = true
edition.workspace = true
rust-version.workspace = true

[lints]
workspace = true

[dependencies]
anyhow.workspace = true
git_utils = { path = "../git_utils" }
